import "./globals.css";
import Providers from "@/components/providers/index";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Exam app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <main className="min-h-screen ">{children}</main>
        </Providers>
      </body>
    </html>
  );
}